# .github/workflows/release-excelUI.yml
name: Release-excelUI
on:
  push:
    branches: [ main ]
    paths:
      - apps/xlam/excelUI.xlam
      - apps/cmd/excelUIsetup.cmd
jobs:
  release:
    runs-on: windows-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          tag_prefix: excelUI-v
      - run: >
          New-Item -ItemType Directory -Force -Path apps\rel | Out-Null;
          Compress-Archive -Path
          apps\xlam\excelUI.xlam,apps\cmd\excelUIsetup.cmd
          -DestinationPath apps\rel\excelUI.zip -Force
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          generate_release_notes: true
          files: apps/rel/excelUI.zip
